create extension if not exists pgcrypto;

create table if not exists public.teachers (
  id uuid primary key default gen_random_uuid(),
  email text not null unique,
  name text,
  created_at timestamptz not null default now()
);

create table if not exists public.students (
  id uuid primary key default gen_random_uuid(),
  teacher_id uuid not null references public.teachers(id) on delete cascade,
  name text not null,
  grade text not null,
  school text,
  target_dept text,
  naesin_data jsonb,
  segibu_pdf_url text,
  segibu_analysis jsonb,
  created_at timestamptz not null default now()
);

create index if not exists students_teacher_created_idx
  on public.students (teacher_id, created_at desc);

comment on column public.students.naesin_data is
  'UNITHING JSONB workspace: service1 snapshot, university_picks, seteuk_latest/records, roadmap_latest.';

comment on column public.students.segibu_analysis is
  'Structured student-record analysis generated by UNITHING Service3.';

alter table public.teachers enable row level security;
alter table public.students enable row level security;

drop policy if exists teachers_no_anon_direct_access on public.teachers;
create policy teachers_no_anon_direct_access
  on public.teachers
  for all
  to anon
  using (false)
  with check (false);

drop policy if exists students_no_anon_direct_access on public.students;
create policy students_no_anon_direct_access
  on public.students
  for all
  to anon
  using (false)
  with check (false);

-- The production Next.js app should use SUPABASE_SERVICE_ROLE_KEY only in server routes.
-- Service-role requests bypass RLS, while route code enforces teacher_id isolation from NextAuth.
-- Do not expose SUPABASE_SERVICE_ROLE_KEY through NEXT_PUBLIC_* environment variables.
